config/routes.rb
Wecare::Application.routes.draw do
  get "events/new"

  get "events/create"

  get "events/show"

  get "events/destroy"

  get "events/index"

  get "events/edit"

  get "topics/index"

  get "users/edit"

  
  get "comments/new"

  get "comments/create"

  resources :posts

resources :comments
resources :sessions, :only => [:new, :create, :destroy]
resources :microposts, :only =>[:new,:create, :edit,:destroy]
resources :topics
resources :events

  
  resources :users
  resources :microposts

match '/home',        :to => 'pages#home'
match '/signup',      :to => 'users#new'
match '/signin',      :to => 'sessions#new'
match '/signout',     :to => 'sessions#destroy'
match '/addtopic',    :to => "microposts#new"
match '/addevent',       :to => 'events#new'
 

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
  	@title = "Wecare Topics"
  	@microposts = Micropost.all
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
<table class="profile" summary="Profile Information">
	<tr> 
		<td class="main">
			
				<%if @microposts.any? %>
					<h1><%= @title %></h1>
				<div id="box-table-a">			 
							
				<table >
					 <tr>
						
						 <th>Name</th>
						 <th>comments</th>
						 <th>Posted</th>
						 <th>delete</th>
						 <th>edit</th>
					 </tr>
				 
				 		<% @microposts.each do |topic| %>
				 	<tr>
				 		<td>
				 			<%=link_to topic.name, topic %>
				 		</td>
				 		<td>
							<%= topic.comments.count%>
																
				 		</td>
				 		<td>
							<%= time_ago_in_words(topic.created_at) %>
																
				 		</td>
				 		<% if current_user.admin || current_user.id == topic.user.id%>
				 		<td>
							<%=link_to "delete", topic, :method => :delete,data: { confirm: 'Are you sure?' } %>																
				 		</td>
				 		<td>
				 			<%=link_to "edit", edit_micropost_path(topic)%>
				 		</td>
				 		
				 		
				 		<% end %>
				 	</tr>

				 <% end %>
				
				</table>

			
</div>

<% else %>
<p>
	<h1>
		No Topics!
	</h1>
</p>
<% end %>
<%=link_to "New Topic", addtopic_path %>
<%=link_to "Back", home_path %>

		</td>
		
	</tr>
</table>