config/routes.rb
Wecare::Application.routes.draw do
  get "events/new"

  get "events/create"

  get "events/show"

  get "events/destroy"

  get "events/index"

  get "events/edit"

  get "topics/index"

  get "users/edit"

  
  get "comments/new"

  get "comments/create"

  resources :posts

resources :comments
resources :sessions, :only => [:new, :create, :destroy]
resources :microposts, :only =>[:new,:create, :edit,:destroy]
resources :topics
resources :events

  
  resources :users
  resources :microposts

match '/home',        :to => 'pages#home'
match '/signup',      :to => 'users#new'
match '/signin',      :to => 'sessions#new'
match '/signout',     :to => 'sessions#destroy'
match '/addtopic',    :to => "microposts#new"
match '/addevent',       :to => 'events#new'
 

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :end_date, :name, :on_date, :user_id
  belongs_to :user
   validates :name, :presence		=> true,
   					:length => { :maximum => 50}


   	validates :description,	:presence  => true,
   							:length => { :maximum => 1000}


   	validates  :on_date,	:presence	=> true
   	validates  :end_date, 	:presence	=> true

   	validates  :user_id, 	:presence	=> true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @title = "New Event"
    @event = Event.new
  end

  def create
    @event = current_user.events.build(params[:event])

    if  @event.save
      redirect_to events_path, :flash => {:sucsess => "Topic added successfully!"}

    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])

  end

  def destroy
    @event = Event.destroy(params[:id])
    redirect_to events_path,:flash => {:sucsess => "Topic deleted successfully!"}
  end

  def index
    @title ="Events"
    @events = current_user.events
  end

  def edit
    @title = " Update event"
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
   if @event.update_attributes(params[:event])
    redirect_to events_path, :flash => {:success => " Event updated!"}
   else
    render 'edit'
     end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_form.html.erb
<h1><%= @titile %></h1>
<%= form_for(@event) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%=f.label :name%><br/>
		<%=f.text_field :name %>
	</div>
	<div class="field">
		<%=f.label :on_date%><br/>
		<%=f.text_field :on_date %>
	</div>
	<div class="field">
		<%=f.label :end_date%><br/>
		<%=f.text_field :end_date %>
	</div>
	<div class="field">
		<%=f.label :description %><br/>
		<%=f.text_area :description %>
	</div>
	<div class="field">
	<%= f.submit "Submit"%>			
	</div>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1><%= @titile %></h1>
<%= form_for(@event) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%=f.label :name%><br/>
		<%=f.text_field :name %>
	</div>
	<div class="field">
		<%=f.label :on_date%><br/>
		<%=f.text_field :on_date %>
	</div>
	<div class="field">
		<%=f.label :end_date%><br/>
		<%=f.text_field :end_date %>
	</div>
	<div class="field">
		<%=f.label :description %><br/>
		<%=f.text_area :description %>
	</div>
	<div class="field">
	<%= f.submit "Edit"%>			
	</div>
<% end %>

app/views/events/index.html.erb
<table class="microposts" summary="Events Information">
	<tr> 
		<td class="main">
			
				<%if @events.any? %>
					<h1><%= @title %></h1>
				<div id="box-table-a">			 
							
				<table >
					 <tr>
						
						 <th>Name</th>
						 <th>Posted</th>
						 <th>delete</th>
						 <th>edit</th>
					 </tr>
				 
				 		<% @events.each do |event| %>
				 	<tr>
				 		<td>
				 			<%=link_to event.name, event %>
				 		</td>
				 		<td>
							<%= time_ago_in_words(event.created_at) %>
																
				 		</td>
				 		<td>
							<%=link_to "delete", event, :method => :delete,data: { confirm: 'Are you sure?' } %>																
				 		</td>
				 		<td>
				 			<%=link_to "edit", edit_event_path(event)%>
				 		</td>
				 	</tr>

				 <% end %>
				
				</table>

			
</div>

<% else %>
<p>
	<h1>
		No Events Created Yet!
	</h1>
</p>
<% end %> 
<%=link_to "New Event", addevent_path %>
<%=link_to "Back", home_path %>
		</td>
		
	</tr>
</table>

app/views/events/new.html.erb
<h1><%= @titile %></h1>
<%= form_for(@event) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%=f.label :name%><br/>
		<%=f.text_field :name %>
	</div>
	<div class="field">
		<%=f.label :on_date%><br/>
		<%=f.text_field :on_date %>
	</div>
	<div class="field">
		<%=f.label :end_date%><br/>
		<%=f.text_field :end_date %>
	</div>
	<div class="field">
		<%=f.label :description %><br/>
		<%=f.text_area :description %>
	</div>
	<div class="field">
	<%= f.submit "Submit"%>			
	</div>
<% end %>

app/views/events/show.html.erb
  <title><%= @title %></title>
  


<h1> <%=@event.name%> </h1>
<table class="event_dates">
	<tr>
		<td>
			<p>On_date: <%= @event.on_date%></p>
			<p>End_date: <%= @event.end_date%></p>
		</td>
	</tr>
</table>
<div class="comman_scroll">
<table>
	<tr>
		<td>
			<p><%= @event.description %></p>
		</td>
	</tr>
</table></div>



 