config/routes.rb
Wecare::Application.routes.draw do
  get "events/new"

  get "events/create"

  get "events/show"

  get "events/destroy"

  get "events/index"

  get "events/edit"

  get "topics/index"

  get "users/edit"

  
  get "comments/new"

  get "comments/create"

  resources :posts

resources :comments
resources :sessions, :only => [:new, :create, :destroy]
resources :microposts, :only =>[:new,:create, :edit,:destroy]
resources :topics
resources :events

  
  resources :users
  resources :microposts

match '/home',        :to => 'pages#home'
match '/signup',      :to => 'users#new'
match '/signin',      :to => 'sessions#new'
match '/signout',     :to => 'sessions#destroy'
match '/addtopic',    :to => "microposts#new"
match '/addevent',       :to => 'events#new'
 

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
	<ul>
		<li>
			<%=link_to "About", '#'%>
		</li>
		<li>
			<%=link_to "Contact", '#' %>
		</li>
		<li>
			<%=link_to "News", 'http://news.railstutorial.org/' %>
		</li>
		<li>
			<%=link_to "Rails Tutorials", 'http://http://railstutorial.org' %>
		</li>
	</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= image_tag("wecare_img.jpg",:alt => "SampleApp", :class => "round") %>
	<nav class= "header">
		<ul>
			<li>
				<%=link_to "Home", home_path %>

				
			</li>
			<%  if signed_in?%>
			<li>
				<%= link_to "Wecare Topics", topics_path %>
			</li>
				<li> 
					<%=link_to "Topics", microposts_path%>
				</li>
				<li> 
					<%=link_to "Events", events_path%>
				</li>
				<li> 
					<%=link_to "Sign out", signout_path%>
				</li>
				
			<% else %>
				<li>
					<%= link_to "Sign in", signin_path %>
				</li>
		<% end %>
		</ul>
	</nav>
</header>
<p>

app/views/layouts/_stylesheets.html.erb
 <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "blueprint/screen", :media => "screen" %>
   <%= stylesheet_link_tag    "blueprint/print", :media => "print" %>
   
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'custom', :media => 'screen'%>
 <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  
<%= render 'layouts/stylesheets'%>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= render 'layouts/header' %>
<section class="round">
<% flash.each do |key, value|%>
<div class ="flash <%= key %>"><%= value%></div>
<% end %>
<%= yield %>
</section>

</div>
 <%= render 'layouts/footer' %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>